import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import BackgroundBlobs from "@/components/BackgroundBlobs/backgroundBlobs";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
    weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${rubik.variable} antialiased`}>
                <BackgroundBlobs />
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}